version: '3.5'
services:
  app:
    build:
     context: ./docker/app
     dockerfile: Dockerfile
    image: sreej32h/phpapp:latest
    networks:
      - appnet
    volumes:
      - ./application:/var/www/app
      - ./docker/app/conf:/var/www/conf
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www/app
  cache:
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - appnet
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
  node:
      build:
        context: ./docker/node
        dockerfile: Dockerfile
      image: sreej32h/node:latest
      networks:
       - appnet
      volumes:
       - ./application:/opt
      working_dir: /opt
      command: echo hi
networks:
  appnet:
    name: ${APP_NETWORK}
    driver: bridge
volumes:
  cachedata:
    driver: local